-- MySQL Script generated by MySQL Workbench
-- Wed Sep 14 19:28:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portal` DEFAULT CHARACTER SET utf8 ;
USE `portal` ;

-- -----------------------------------------------------
-- Table `portal`.`moderadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`moderadores` (
  `id_moderador` INT NOT NULL AUTO_INCREMENT,
  `nombre_mod` VARCHAR(45) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_moderador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `direccion` VARCHAR(90) NOT NULL,
  `ciudad` VARCHAR(90) NOT NULL,
  `telefono` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT UNSIGNED NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal`.`resenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`resenas` (
  `id_resena` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_moderador` INT NOT NULL,
  `titulo` VARCHAR(90) NOT NULL,
  `contenido` TEXT NOT NULL,
  `calificacion` TINYINT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_resena`),
  INDEX `id_moderador_idx` (`id_moderador` ASC) VISIBLE,
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `portal`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_moderador`
    FOREIGN KEY (`id_moderador`)
    REFERENCES `portal`.`moderadores` (`id_moderador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `fecha_facturacion` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_ventas`),
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `portal`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `portal`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
